[build-system]
requires = [
    "setuptools",
    "wheel",
    "ninja",
    "cmake",
    "typing-extensions",
]
# Use legacy backend to import local packages in setup.py
build-backend = "setuptools.build_meta"

[tool.black]

line-length = 100
indent-width = 4
target-version = ["py38", "py39", "py310"]
extend-exclude="*/build"
ignore-long-lines=^\s*(# )?<?https?://\S+>?$
