kind: Pod
apiVersion: v1
spec:
  # The shared volume named "artifacts".
  # NOTE: `emptyDir: { }` declares an empty temporary volume, and
  #       will be removed after all jobs are finished.
  volumes:
  - name: artifacts
    emptyDir: { }
  - name: shm-volume
    emptyDir:
      medium: Memory
      sizeLimit: 10G
  - name: integration-data-local
    hostPath:
      path: /home/mccxadmin/torch_musa_integration/data
      type: Directory
  - name: integration-data-shared
    hostPath:
      path: /juicefs/torch_musa_integration/data
      type: Directory
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gputype
            operator: In
            values:
            - mthreads-train-s80
  containers:
  - name: main
    tty: true
    image: sh-harbor.mthreads.com/mt-ai/musa-pytorch-dev-py38:dev3.0.0-v1.1.0-qy1
    imagePullPolicy: Always
    env:
    - name: TARGET_DEVICE
      value: musa
    - name: PYTORCH_REPO_PATH
      value: /home/pytorch
    - name: MUSA_VISIBLE_DEVICES
      value: all
    - name: MTHREADS_VISIBLE_DEVICES
      value: all
    command:
    - sleep
    securityContext:
       privileged: true
    args:
    - infinity
    # Mount the volume named "artifacts" to path "/artifacts", readwrite
    volumeMounts:
    - mountPath: /artifacts
      name: artifacts
      readOnly: false
    - mountPath: /dev/shm
      name: shm-volume
    - mountPath: /data/torch_musa_integration/local
      name: integration-data-local
      readOnly: true
    - mountPath: /data/torch_musa_integration/shared
      name: integration-data-shared
      readOnly: true
