kind: Pod
apiVersion: v1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gputype
            operator: In
            values:
            - mthreads-train
  containers:
  - name: main
    tty: true
    image: sh-harbor.mthreads.com/mt-ai/musa-pytorch-dev:latest
    imagePullPolicy: Always
    env:
    - name: TARGET_DEVICE
      value: musa
    - name: PYTORCH_REPO_PATH
      value: /home/pytorch
    command:
    - sleep
    args:
    - infinity
    resources:
      limits:
        cpu: "32"
        memory: "128Gi"
