# -*- coding: utf-8 -*-
# pylint: disable=C0301, C0305
#
# Torch_MUSA documentation build configuration file.
#
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
from __future__ import print_function

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# import sys
# reload(sys)
# sys.setdefaultencoding('utf-8')
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.doctest",
    "sphinx.ext.mathjax",
    "sphinx.ext.imgmath",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "摩尔线程Torch_MUSA开发者手册"
copyright_str = "5025, MooreThreads"
author = ""

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "2.0.0"
# The full version, including alpha/beta/rc tags.
release = version
curfnpre = "MooreThreads-Torch_MUSA-Developer-Guide-CN-v"
curfn = curfnpre + version + ".tex"
today = ""

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "zh_CN"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "_venv", "_templates"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

smartquotes = False
numfig = True
numfig_secnum_depth = 1
# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
html_permalinks = False
html_copy_source = False
html_css_files = [
    "custom.css",
]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    "**": [
        "relations.html",  # needs 'show_related': True theme option to display
        "searchbox.html",
    ]
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "Torch_MUSAdoc"


# -- Options for LaTeX output ---------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, curfn, "摩尔线程Torch\_MUSA开发者手册", author, "manual"),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        "MooreThreads-Torch_MUSA-Developer-Guide-CN",
        "MooreThreads Torch MUSA User Guide",
        [author],
        1,
    )
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "MooreThreads-Torch_MUSA-Developer-Guide-CN",
        "MooreThreads Torch MUSA User Guide",
        author,
        "MooreThreads",
        "One line description of project.",
        "Miscellaneous",
    ),
]


latex_engine = "xelatex"

latex_logo = "./logo.png"


latex_show_urls = "footnote"

latex_use_xindy = False
latex_elements = {
    "papersize": "a4paper",
    "inputenc": "",
    "utf8extra": "",
    "figure_align": "H",
    "releasename": "版本",
    "sphinxsetup": """
    verbatimwithframe=false,
    verbatimwrapslines=true,
    VerbatimColor={RGB}{220,220,220},
    verbatimhintsturnover=false,
""",
    # Additional stuff for the LaTeX preamble.
    "preamble": """
\\addto\\captionsenglish{\\renewcommand{\\chaptername}{}}

\\usepackage{xcolor}
\\usepackage{eso-pic}
\\usepackage{wallpaper}
\\usepackage{tocbibind}
\\usepackage{enumitem}
\\usepackage{tcolorbox}
\\usepackage{listings}
\\usepackage{framed}
\\usepackage{color}


\\titleformat{\\chapter}{\\raggedleft\\huge\\bfseries\\color{darkgray}}{\\thechapter}{0.1em}{}
\\titlespacing{\\chapter}{0pt}{5pt}{2pt}
\\definecolor{noteframecolor}{RGB}{91,163,235}
\\definecolor{notebackcolor}{RGB}{222,237,251}
\\definecolor{warningframecolor}{RGB}{235,162,28}
\\definecolor{warningbackcolor}{RGB}{255,247,236}
\\definecolor{hintframecolor}{RGB}{70,193,196}
\\definecolor{hintbackcolor}{RGB}{226,254,249}
\\definecolor{mtorange}{RGB}{252,103,26}
\\renewcommand{\\labelitemi}{$\\vcenter{\\hbox{\\scriptsize$\\bullet$}}$}
\\definecolor{shadecolor}{RGB}{220,220,220}

% 设置字体

\\usepackage{xeCJK}
\\usepackage{fontspec}
\\xeCJKsetup{CJKspace=true}
\\defaultfontfeatures[\\rmfamily,\\sffamily,\\ttfamily]{}
\\setCJKmainfont{Noto Sans CJK SC}[AutoFakeSlant]
\\setCJKsansfont{Noto Sans CJK SC}[AutoFakeSlant]
\\setCJKmonofont{Noto Sans Mono CJK SC}[AutoFakeSlant]
\\setmainfont{Noto Sans CJK SC}[AutoFakeSlant]

% 段首缩进 2 格

%\\usepackage{indentfirst}
%\\setlength{\\parindent}{2em}

\\usepackage{setspace}

% 1.5 倍行间距
\\renewcommand{\\baselinestretch}{1.5}
% 表格里的行间距
\\renewcommand{\\arraystretch}{1.5}

% list 列表的缩进对齐
\\usepackage{enumitem}
\\setlist{nosep}

% 表格类的宏包
\\usepackage{threeparttable}
\\usepackage{array}
\\usepackage{booktabs}

% fancy 页眉页脚
\\usepackage{fancyhdr}
\\pagestyle{fancy}

% 在 sphinx 生成的 tex 文件里，normal 是指普通页面（每一个章节里，除了第一页外剩下的页面）
% 页眉，L：left，R：right，E：even，O：odd
% 奇数页面：左边是 leftmark，章号和章名称；右边是 rightmark，节号与节名称
% 偶数页面：左边是 rightmark，节号与节名称；右边是 leftmark，章号和章名称
% textsl 是字体，slanted shape，对于英语而言，某种斜体。但是不同于 textit 的 italic shape
% 左页脚：版权信息
% 右页脚：页码数
% rulewidth：页眉和页脚附近的横线的粗细，当设置为 0pt 时，就没有该横线
%
\\fancypagestyle{normal} {
\\fancyhf{}
\\fancyhead{}
\\fancyhead[LE,RO]{\\textsl{\\rightmark}}
\\fancyhead[LO,RE]{\\textsl{\\leftmark}}
\\lfoot{Copyright © 2025 MooreThreads Corporation.}
\\rfoot{\\thepage}
\\renewcommand{\\headrulewidth}{0.4pt}
\\renewcommand{\\footrulewidth}{0.4pt}
}

% 在 sphinx 生成的 tex 文件里，plain 是指每个章节的第一页等
\\fancypagestyle{plain} {
\\fancyhf{}
% left head 还可以内嵌图片，图片可以是 pdf，png，jpeg 等
% \\lhead{\\includegraphics[height=4pt]{cn_tm.pdf}}
\\lhead{\\large\\textcolor[rgb]{0.9882,0.4039,0.1020}{MooreThreads®}}
\\lfoot{Copyright © 2025 MooreThreads Corporation.}
\\rfoot{\\thepage}
\\renewcommand{\\headrulewidth}{0.4pt}
\\renewcommand{\\footrulewidth}{0.4pt}
}
\\tolerance=100000
\\emergencystretch=\\maxdimen
\\hyphenpenalty=10000
\\hbadness=10000
""",
    "printindex": r"\footnotesize\raggedright\printindex",
    "extraclassoptions": "openany,oneside,table",
}  # latex_elements

import os
import os.path as osp
import sys

sys.path.append(osp.join(osp.dirname(__file__), "../"))

import modify_latex

latex_content = ""


def config_inited_handler(app, config):
    global latex_content
    latex_content = config.latex_documents
    try:
        app.require_sphinx("3.5")
        config.latex_elements["sphinxsetup"] = (
            "verbatimforcewraps=true,verbatimmaxunderfull=2,"
            + config.latex_elements["sphinxsetup"]
        )
    except Exception as e:
        pass


def build_finished_handler(app, exception):
    if exception != None:
        return
    modify_latex.modify_latex(app.outdir, latex_content)


def setup(app):
    app.connect("config-inited", config_inited_handler)
    app.connect("build-finished", build_finished_handler)
